- api/endpoints/bot_chats_router.py
- api/endpoints/bot_comments_router.py
- api/endpoints/bot_posts_router.py
Close #46 
- 중복된 라우터 엔드포인트 경로 제거
f7d5c6850d6e4df1c7d798da79ea70ca5fceeb9e
-
> [STYLE] 라우터 엔드포인트 중복된 경로 제거

- api/endpoints/controllers/bot_posts_controller.py
- core/prompt_templates/bot_posts_prompt.py
- schemas/bot_chats_schema.py
- schemas/bot_comments_schema.py
- schemas/bot_common_schema.py
- schemas/bot_posts_schema.py
- services/bot_chats_service.py
- services/bot_comments_service.py
- services/bot_posts_service.py
- utils/error_handler.py
Close #58 
api 명세서 변경으로인한 소셜봇 게시물 작성 기능 전반적 수정 작업
- schema
- request용, response용 분리
- schemas/bot_common_schema.py 생성
- schemas/bot_posts_schema.py, schemas/bot_chats_schema.py, schemas/bot_comments_schema.py 에서 공통적으로 사용하는 클래스는 schemas/bot_common_schema.py로 따로 분리
-  post 관련
- 새로 정의한 schema와 api 명세서의 예외처리에 맞도록 controller, service,  prompt, error_handler 수정
- 새로 정의한 schema에 맞춰서 comments랑 chats 부분들 class명 수정함.
- eda8570091542d8bb1605c22a38f666ff2f42e6a
- 41f2c0631a75bb003ef7ab08f67d2ce9c86d4136
- 8f4dc1f518f090212adc753fe0a5a1057669cf97
> Breaking change/58 social bot api schema update

- main.py
Close #68 
- CORS 미들웨어 구현
4f19d2973ad404148a50e00a46b87542efd6b42f
> [FEAT] CORS 미들웨어 설정

- api/endpoints/bot_chats_router.py
- api/endpoints/bot_posts_router.py
- api/endpoints/bot_recomments_router.py
- api/endpoints/youtube_summary_router.py
Close #75 
- Controller 객체 생성 부분 수정
7b52199f6204211774f2e561fac767ca79f5b93d
> [FIX] Controller 객체 생성 수정

- schemas/youtube_summary_schema.py
- services/youtube_summary_service.py
Close #77 
- YouTubeSummaryRequest 타입 변경 
- HttpUrl -> str
46bbb0579db00b0e71b7efb65b6895d2ef2a3aa3
> [REFACTOR] YouTubeSummaryRequest 타입 변경

- models/koalpha_loader.py
Close #80 
- KoalphaLoader.get_response 에서 메시지 리스트를 수동으로 문자열 조합하던 방식을 대체하여, transformers.AutoTokenizer.apply_chat_template 기반으로 자동으로 prompt 문자열을 생성하도록 기능을 추가했습니다.
- 동시에 SamplingParams 의 stop 토큰 설정과 스코프 참조 문제를 해결하여, 모델 생성 중단 조건이 정확하고 NameError 없이 정상 동작하도록 버그를 수정했습니다.
-946c1ddeb8d38b053784aca1b68e37c3567eb28f
> [FEAT] apply_chat_template 기반 messages -> prompt 자동 변환 지원

- .gitignore
- core/prompt_templates/bot_posts_prompt.py
- core/prompt_templates/bot_recomments_prompt.py
- core/prompt_templates/youtube_summary_prompt.py
- requirements.txt
- services/bot_posts_service.py
- services/bot_recomments_service.py
- services/youtube_summary_service.py
#82 
- ai 기능(소셜봇 게시물 작성, 소셜봇 대댓글 작성, 유튜브 요약)에 대한 프롬프트를 쉽게 버저닝하고, 각 프롬프트에 대한 output값을 tracking하기 위해서 도입.
> 해당 변경사항은 colab에서만 테스트되었음을 알립니다.
1. langfuse와 관련해서 requirements.txt가 수정되었습니다.
2. social bot의 persona관련 파일이 .gitignore에 업데이트 되었습니다.
3. .env에 langfuse관련 api key가 업데이트 되었습니다.
4. .env에 `MODEL_PATH`와 `PERSONA_PATH`가 업데이트 되었습니다.
5. 각 ai 기능별로 prompt.py 파일내에 텍스트로 적혀있던 프롬프트를 langfuse로 옮겨서 연동시켰습니다.
6. 각 ai 기능별로 prompt.py 파일내에 .env에 적혀있는 langfuse관련 api key를 설정했습니다.
7. 실행 모드에 따라 프롬프트의 label을 다르게 설정했습니다.
```python
if mode == "gcp" : label="production"
else : label="latest"
``` 
8. 각 ai 별로 service.py에서 프롬프트와 그에 대한 모델의 응답, 응답 시간을 trace로 기록했습니다.
- !!! `requirements.txt `!!!가 수정되었습니다.(langfuse관련)
> [FEAT] 프롬프트 버저닝을 위한 langfuse 도입 - colab 테스트 완료

- core/prompt_templates/bot_recomments_prompt.py
- models/koalpha_loader.py
- services/bot_posts_service.py
- services/bot_recomments_service.py
Close #84 
- 모델 응답에서 ":" 앞에 있는 텍스트 삭제
- 모델 응답에서 [ ] 사이에 있는 텍스트 삭제
- colab에서 테스트 완료
7f72089f60735dc40eb9789816ecd5fc3c91e47b
> [FIX] 소셜봇 응답을 정제하기 위해 후처리 코드 추가

- api/endpoints/bot_chats_router.py
- api/endpoints/bot_posts_router.py
- api/endpoints/bot_recomments_router.py
Close #90 
- 소셜봇 엔드포인트에서 "/"붙어서 307 에러 반환
cdd18d937b655f5dff4df93ba3c161e63ecd224b
> [FIX] 엔드포인트 끝에 "/" 삭제

- models/koalpha_loader.py
Close #89 
- colab 서버와 gcp 서버에서의 vLLM 파라미터 통일
3afb5abcd126220a08c6e3fa8e9a01c969301e95
> [FIX] colab - gcp 버전 모델 파라미터 통일

- utils/logging_discord.py
Close #https://github.com/100-hours-a-week/22-tenten-ai/issues/110
- 디스코드 웹훅 로컬 제외
utils/logging_discord.py
> [HOTFIX] 디스코드 웹훅 전송 로컬 제외 시키기 

- utils/logging_discord.py
Close #https://github.com/100-hours-a-week/22-tenten-ai/issues/112 7eabd1a
- 오타수정
logging_discord.py
> [HOTFIX] 디스코드 웹훅 전송 로컬 제외 코드 중 오타 수정

- requirements.txt
Close #118 
- protobuf의 의존성 충돌 문제 해결
8b355f58086d13e6f37b20540640a78eaa67451c
> [FIX] protobuf 의존성 충돌 문제 해결

- core/prompt_templates/bot_posts_prompt.py
- core/prompt_templates/bot_recomments_prompt.py
- core/prompt_templates/youtube_summary_prompt.py
- main.py
- models/model_loader.py
- services/bot_posts_service.py
- services/bot_recomments_service.py
- services/youtube_summary_service.py
- utils/logging_discord.py
Close #131 
- CICD 구축을 위한 환경변수 참조 변경
302dac0fb5aa85c9ba63707d0230e2a133962845
> [DOCS] CICD 구축을 위한 환경변수 참조 변경

- Dockerfile
- models/model_loader.py
- services/bot_posts_service.py
- services/bot_recomments_service.py
- services/youtube_summary_service.py
- utils/logging_discord.py
Close #136 
- dotenv 경로명 수정
.env -> env
> [HOTFIX] Cloud Secret Manager .env 경로명 수정 #136

- Dockerfile
Close #143
- cmd, env 변경
api -> api-prod
> [HOTFIX] Dockerfile cmd 수정

- core/prompt_templates/bot_posts_prompt.py
- core/prompt_templates/bot_recomments_prompt.py
- core/prompt_templates/youtube_summary_prompt.py
- models/model_loader.py
- services/bot_posts_service.py
- services/bot_recomments_service.py
- services/youtube_summary_service.py
- utils/logging_discord.py
Close #148
- env 환경변수 참조 경로 수정
.env -> env
> [FIX] env 환경변수 참조 경로 수정

- requirements.txt
Close #130 
- 유투브 자막 라이브러리 업데이트
5eff4461af301853a899b437d440596ff9fd2c58
> [FIX] 유투브 자막 라이브러리 업데이트

- Dockerfile
Close #153
- install requirements.txt -> requirements-gcp.txt
- install requirements.txt -> requirements-gcp.txt
> [DOCS] Dockerfile 수정pip install requirements-gcp

- Dockerfile
Close #161 
- copy requirements.txt 추가
- copy requirements.txt 추가
> [HOTFIX] Dockerfile install requirements.txt 명령어 실행시 오류

- Dockerfile
- entrypoint.sh
Close #170
- Dockerfile cmd 수정
- entrypoint.sh 추가
- Cloud Build 트리거 변수 추가(develp, main 브랜치 별 실행 명령어 분리)
- Dockerfile cmd 수정
- entrypoint.sh 추가
> [FEAT] Dockerfile 브랜치별 명령어 분기처리

- Dockerfile
> [FEAT] Dockerfile 브랜치별 명령어 분기처리 feature 새로운 기능 추가(버그수정)

- core/prompt_templates/bot_posts_prompt.py
- core/prompt_templates/bot_recomments_prompt.py
- core/prompt_templates/youtube_summary_prompt.py
- main.py
- models/model_loader.py
- services/bot_recomments_service.py
- services/youtube_summary_service.py
- utils/logging_discord.py
Close #174 
- Gemini API에서 HyperCLOVAX로의 모델 교체로 인한 CLI 인자 추가 및 환경변수 참조 변경
672b1378958cd66275abd4cd28dd49313ec1c7d9
> [Docs] 모델 교체에 따른 환경변수 참조 변경

- entrypoint.sh
Close #176 
- 모델 교체에 따른 /bin/sh 명령어 수정
- gcp -> gcp-prod
> [AI - DOCS] 모델 교체에 따른 명령어 변경

- api/endpoints/bot_chats_router.py
- api/endpoints/controllers/bot_chats_controller.py
- core/prompt_templates/bot_chats_prompt.py
- core/sse_manager.py
- docs/bot_chats_service.md
- main.py
- requirements-gcp.txt
- schemas/bot_chats_schema.py
- services/bot_chats_service.py
- tests/test_bot_chats_service.py
Close #167
- 실시간으로 사용자와 상호작용하는 소셜 챗봇 기능을 새롭게 구현
- SSE(Server-Sent Events)를 이용한 스트리밍 응답
- 대화 맥락을 기억하는 메모리
- Langfuse를 통한 디버깅 및 프롬프트 관리
- 챗봇 핵심 기능 신규 구현:
- SSE 기반 실시간 채팅 API 엔드포인트(POST /chats/bot/stream)를 추가했습니다.
- BotChatsService를 도입하여 채팅 비즈니스 로직을 관리하고, stream_id를 기준으로 대화 세션을 관리합니다.
- LangChain의 ConversationBufferWindowMemory를 이용해 대화 맥락(최근 5개 메시지)을 기억하는 기능을 구현했습니다.
- Langfuse 연동:
- 챗봇의 모든 대화 흐름을 추적하고 디버깅할 수 있도록 Langfuse 트레이스를 연동했습니다.
- Langfuse PromptManagement를 적용하여 챗봇의 페르소나와 시스템 프롬프트를 원격으로 관리합니다.
- 안정성 및 사용성 개선:
- 개발 과정에서 발견된 대화 기록 저장 오류 및 세션 초기화 버그를 수정했습니다.
- main.py의 dotenv 로딩 시점을 조정하여 환경 변수 관련 문제를 해결했습니다.
- 사용자 경험 향상을 위해 챗봇 응답 시 단어 단위로 전송되는 스트리밍을 구현했습니다.
- `requirements-gcp`가 업데이트 됐습니다!
- 현재 Langfuse 프롬프트는 환경과 무관하게 production 버전을 사용하도록 고정되어 있습니다. load_dotenv 호출 순서 문제에 대한 근본적인 해결을 위해 …
> [FEAT] 소셜봇 채팅 기능 구현
